export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_HANDLE = 'GET_PROFILE_HANDLE';

export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const GET_PROFILE_HANDLE_PENDING = 'GET_PROFILE_HANDLE_PENDING';
export const GET_PROFILE_HANDLE_SUCCESS = 'GET_PROFILE_HANDLE_SUCCESS';
export const GET_PROFILE_HANDLE_FAILURE = 'GET_PROFILE_HANDLE_FAILURE';

export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILES_PENDING = 'GET_PROFILES_PENDING';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAILURE = 'GET_PROFILES_FAILURE';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';